export const EPOCHS = {
	UNIX: BigInt(0),
	TWITTER: BigInt(1288834974657),
	DISCORD: BigInt(1420070400000)
};

export const DEFAULT_VALUE = BigInt(0);
export const DEFAULT_SEQUENCE = DEFAULT_VALUE;

export const USIGNED_INCREASE = BigInt(1);
export const SIGNED_INCREASE = BigInt(-1);

export const WORKER_ID_BITS = BigInt(5);
export const PROCESS_ID_BITS = BigInt(5);
export const SEQUENCE_BITS = BigInt(12);

export const WORKER_ID_DECONSTRUCT_MASK = BigInt(0x3E0000);
export const PROCESS_ID_DECONSTRUCT_MASK = BigInt(0x1F000);

export const WORKER_ID_MASK = SIGNED_INCREASE ^ (SIGNED_INCREASE << WORKER_ID_BITS);
export const PROCESS_ID_MASK = SIGNED_INCREASE ^ (SIGNED_INCREASE << PROCESS_ID_BITS);
export const SEQUNCE_MASK = SIGNED_INCREASE ^ (SIGNED_INCREASE << SEQUENCE_BITS);

export const TIMESTAMP_LEFT_SHIFT = SEQUENCE_BITS + WORKER_ID_BITS + PROCESS_ID_BITS;
export const WORKER_ID_SHIFT = SEQUENCE_BITS + WORKER_ID_BITS;
export const PROCESS_ID_SHIFT = SEQUENCE_BITS;
