export const Epoch = {
	UNIX: 0n,
	TWITTER: 1288834974657n,
	DISCORD: 1420070400000n
};

export const DEFAULT_VALUE = 0n;
export const DEFAULT_SEQUENCE = DEFAULT_VALUE;

export const USIGNED_INCREASE = 1n;
export const SIGNED_INCREASE = -1n;

export const WORKER_ID_BITS = 5n;
export const PROCESS_ID_BITS = 5n;
export const SEQUENCE_BITS = 12n;

export const WORKER_ID_DECONSTRUCT_MASK = 0x3E0000n;
export const PROCESS_ID_DECONSTRUCT_MASK = 0x1F000n;

export const WORKER_ID_MASK = SIGNED_INCREASE ^ (SIGNED_INCREASE << WORKER_ID_BITS);
export const PROCESS_ID_MASK = SIGNED_INCREASE ^ (SIGNED_INCREASE << PROCESS_ID_BITS);
export const SEQUNCE_MASK = SIGNED_INCREASE ^ (SIGNED_INCREASE << SEQUENCE_BITS);

export const TIMESTAMP_LEFT_SHIFT = SEQUENCE_BITS + WORKER_ID_BITS + PROCESS_ID_BITS;
export const WORKER_ID_SHIFT = SEQUENCE_BITS + WORKER_ID_BITS;
export const PROCESS_ID_SHIFT = SEQUENCE_BITS;
